In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop('species',axis = 1)
y = df['species']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [15]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [16]:
model_knn.score(X_test,y_test)

1.0

### SVM

In [17]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(C = 10,kernel = 'rbf',gamma = 'auto')

In [25]:
model_svm1 = SVC(gamma = 'auto')

In [26]:
model_svm1.fit(X_train,y_train)

SVC(gamma='auto')

In [22]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto')

In [23]:
model_svm.score(X_test,y_test)

1.0

### GridSearchCV

In [24]:
from sklearn.model_selection import GridSearchCV

In [27]:
classifier = GridSearchCV((model_svm1),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv = 5,return_train_score=False)

In [28]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [29]:
classifier.cv_results_

{'mean_fit_time': array([0.01057386, 0.00492859, 0.00442386, 0.00485349, 0.00386162,
        0.00369525, 0.00267391, 0.00378685]),
 'std_fit_time': array([0.01049867, 0.00177627, 0.00153547, 0.00048482, 0.00080351,
        0.00045221, 0.00043719, 0.00077428]),
 'mean_score_time': array([0.0045639 , 0.00294676, 0.00274162, 0.00352988, 0.00303731,
        0.00250149, 0.00288248, 0.00274315]),
 'std_score_time': array([1.52160709e-03, 8.05938516e-04, 4.02995995e-04, 9.75854888e-04,
        5.48123432e-05, 5.66290091e-04, 6.13445639e-04, 5.60853397e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [33]:
results = pd.DataFrame(classifier.cv_results_)

In [34]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010574,0.010499,0.004564,0.001522,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004929,0.001776,0.002947,0.000806,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004424,0.001535,0.002742,0.000403,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004853,0.000485,0.003530,0.000976,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003862,0.000804,0.003037,0.000055,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003695,0.000452,0.002501,0.000566,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002674,0.000437,0.002882,0.000613,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003787,0.000774,0.002743,0.000561,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [35]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

### Random search CV

In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
classifier_r = RandomizedSearchCV((model_svm1),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=4,cv = 5,return_train_score=False)

In [39]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [40]:
results = pd.DataFrame(classifier_r.cv_results_)

In [41]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010001,0.013479,0.004654,0.001892,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003931,0.001080,0.002989,0.000980,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004525,0.000338,0.003329,0.000695,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
3,0.003605,0.000558,0.003143,0.000199,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,4

In [42]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1        1       linear         0.980000
2       10       linear         0.973333
3       20          rbf         0.966667